import styles from "./homepage.module.css";
import Link from "next/link";

export default function Home() {
  return <Link href="/asdf">
  <h1>asdfsadfjkagsjkdjkasdgjkhasjhkdgfjhk  jksdafjkadsjkfkj jkhlasdkhjf jkhsad fkhjaskjdfjksadfjk askfldjkls</h1>
  KLoremmipsummsd KLoremmipsummsd oremKLoremmipsummsd  asdasfd  asdfasforemKLoremmipsummsdoremKLoremmipsummsdoremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd oremKLoremmipsummsd orem</Link>;
}
